const fs = require('fs');
const path = require('path');

const dataDir = path.resolve(__dirname, '../data');

const batchDocs = {
    '08-2021-TT-BGDDT': {
        doc_id: "08/2021/TT-BGDĐT",
        title: "Quy định về đào tạo trình độ đại học",
        date: "2021-03-25",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    '17-2021-TT-BGDDT': {
        doc_id: "17/2021/TT-BGDĐT",
        title: "Quy định về chuẩn chương trình đào tạo; xây dựng, thẩm định và ban hành chương trình đào tạo các trình độ của giáo dục đại học",
        date: "2021-06-22",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    'BGDDT-CV-2085': {
        doc_id: "2085/QLCL-KĐCLGD",
        title: "Hướng dẫn tự đánh giá và đánh giá ngoài chương trình đào tạo",
        date: "2020-12-31",
        department: "Ministry of Education and Training",
        type: "Official Letter"
    },
    'BGDDT-CV-774': {
        doc_id: "774/QLCL-KĐCLGD",
        title: "Công văn điều chỉnh phụ lục Công văn 2085/QLCL-KĐCLGD",
        date: "2021-06-10",
        department: "Ministry of Education and Training",
        type: "Official Letter"
    },
    'BGDDT-QD-4998': {
        doc_id: "4998/QĐ-BGDĐT",
        title: "Quy định kỹ thuật về dữ liệu của cơ sở dữ liệu giáo dục và đào tạo",
        date: "2021-12-31",
        department: "Ministry of Education and Training",
        type: "Decision"
    },
    '30-2018-TT-BGDDT': {
        doc_id: "30/2018/TT-BGDĐT",
        title: "Quy chế quản lý người nước ngoài học tập tại Việt Nam",
        date: "2018-12-24",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    'DHVN-KH-2026-50': {
        doc_id: "50/ĐHVN-KT&ĐBCL",
        title: "Kế hoạch triển khai các hoạt động đảm bảo chất lượng của trường Đại học Việt Nhật năm 2026",
        date: "2026-01-19",
        department: "Vietnam Japan University",
        type: "Plan"
    }
};

const disclaimers = {
    vi: "> **[DISCLAIMER]** Tài liệu này được tạo bởi AI phục vụ mục đích học tập và tham khảo. Nội dung gốc tiếng Việt được trích xuất từ văn bản chính thức. Mọi thông tin có tính pháp lý phải được đối chiếu với văn bản gốc có đóng dấu đỏ.",
    en: "> **[DISCLAIMER]** This document was generated by AI for educational and reference purposes. The content is based on the original Vietnamese legal text. For legal purposes, please refer to the official signed Vietnamese version.",
    ja: "> **[DISCLAIMER]** 本文書はAIにより生成されたものであり、学習および参照を目的としています。内容はベトナム語の公式法的文書に基づいています。法的効力については、署名・捺印された公式のベトナム語原文を優先してください。"
};

function processFile(filePath) {
    const filename = path.basename(filePath);
    let prefix = null;
    for (const key in batchDocs) {
        if (filename.startsWith(key)) {
            prefix = key;
            break;
        }
    }
    if (!prefix) return;

    const meta = batchDocs[prefix];
    const lang = filename.endsWith('_en.md') ? 'en' : filename.endsWith('_ja.md') ? 'ja' : 'vi';
    const isTranscription = (lang === 'vi');

    let content = fs.readFileSync(filePath, 'utf-8');
    const today = new Date().toISOString().split('T')[0];

    // 1. Construct YAML
    const yaml = `---
doc_id: "${meta.doc_id}"
title: "${meta.title}"
date: ${meta.date}
department: "${meta.department}"
type: "${meta.type}"
restricted: false
last_updated: ${today}
---`;

    // 2. Remove old YAML, header notes, etc.
    content = content.replace(/^---[\s\S]*?---\n*/, '');
    content = content.replace(/<div class="source-note"[\s\S]*?<\/div>\n*/g, '');
    content = content.replace(/<div class="doc-note"[\s\S]*?<\/div>\n*/g, '');
    content = content.replace(/^> \*\*\[(?:DISCLAIMER|免責事項|TUYÊN BỐ TỪ CHỐI TRÁCH NHIỆM)\]\*\*.*\n*/gm, '');

    let mainBody = content.trim();

    // 3. Normalization logic
    const lines = mainBody.split('\n');
    let newLines = [];
    let titleSectionDone = false;

    for (let i = 0; i < lines.length; i++) {
        let line = lines[i];

        // Normalize existing HTML headers
        line = line.replace(/<h[1-6] align="center">(.*?)<\/h[1-6]>/g, '<p align="center"><strong>$1</strong></p>');

        let cleanLine = line.replace(/^#+ /, '').replace(/\*\*+/g, '').replace(/<[^>]*>/g, '').trim();

        // Check for Chapter/Article markers
        const isChapter = /^(Chương|Chapter|第[0-9一二三四五六七八九十百]+章)/i.test(cleanLine);
        const isArticle = /^(Điều|Article|第[0-9一二三四五六七八九十百]+条)/i.test(cleanLine);

        if (isChapter || isArticle) {
            titleSectionDone = true;
            if (isTranscription) {
                line = (isChapter ? '# ' : '## ') + cleanLine;
            } else {
                // EN/JA: Chapter -> #, Article -> ## (reduces downstream bad_h3_article cleanup)
                line = (isChapter ? '# ' : '## ') + cleanLine;
            }
        } else if (!titleSectionDone && i < 60) {
            // Centering titles
            const isHeaderMarker = line.startsWith('#');
            const isPAlignCenter = line.startsWith('<p align="center">');

            if (cleanLine.length > 0 && !isPAlignCenter && !line.startsWith('---') && !line.startsWith('***') && !line.startsWith('|')) {
                if (isHeaderMarker || (line.startsWith('**') && line.endsWith('**')) || cleanLine.toUpperCase() === cleanLine || (i < 10 && cleanLine.length < 100)) {
                    line = `<p align="center"><strong>${cleanLine}</strong></p>`;
                }
            }
        }

        // List indentation
        if (/^[ \t]+(\d+\.\s+)/.test(line)) {
            line = line.replace(/^[ \t]+(\d+\.\s+)/, '$1');
        }
        if (/^[ \t]{0,1}-\s+(.*)/.test(line)) {
            line = line.replace(/^[ \t]{0,1}-\s+(.*)/, '  - $1');
        }

        newLines.push(line);
    }

    mainBody = newLines.join('\n');
    mainBody = mainBody.replace(/\n{3,}/g, '\n\n');

    const finalContent = `${yaml}\n\n${disclaimers[lang]}\n\n${mainBody}`;

    fs.writeFileSync(filePath, finalContent, 'utf-8');
    console.log(`[PROCESSED] ${filename} (${lang})`);
}

function main() {
    const files = fs.readdirSync(dataDir);
    for (const docPrefix in batchDocs) {
        const docFiles = files.filter(f => f.startsWith(docPrefix) && f.endsWith('.md'));
        docFiles.forEach(file => {
            processFile(path.join(dataDir, file));
        });
    }
}

main();
