const fs = require('fs');
const path = require('path');

const dataDir = path.resolve(__dirname, '../data');

const batchDocs = {
    '18-2021-TT-BGDDT': {
        doc_id: "18/2021/TT-BGDĐT",
        title: "Ban hành Quy chế tuyển sinh và đào tạo trình độ tiến sĩ",
        date: "2021-06-28",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    '23-2021-TT-BGDDT': {
        doc_id: "23/2021/TT-BGDĐT",
        title: "Ban hành Quy chế tuyển sinh và đào tạo trình độ thạc sĩ",
        date: "2021-08-30",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    '01-2024-TT-BGDDT': {
        doc_id: "01/2024/TT-BGDĐT",
        title: "Ban hành Chuẩn cơ sở giáo dục đại học",
        date: "2024-02-05",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    '111-2013-TT-BTC': {
        doc_id: "111/2013/TT-BTC",
        title: "Hướng dẫn thực hiện Luật Thuế thu nhập cá nhân",
        date: "2013-08-15",
        department: "Ministry of Finance",
        type: "Circular"
    },
    '86-2021-ND-CP': {
        doc_id: "86/2021/NĐ-CP",
        title: "Quy định về việc công dân Việt Nam ra nước ngoài học tập, giảng dạy, nghiên cứu khoa học và trao đổi học thuật",
        date: "2021-09-25",
        department: "Government",
        type: "Decree"
    }
};

const disclaimers = {
    vi: "> **[DISCLAIMER]** Tài liệu này được tạo bởi AI phục vụ mục đích học tập và tham khảo. Nội dung gốc tiếng Việt được trích xuất từ văn bản chính thức. Mọi thông tin có tính pháp lý phải được đối chiếu với văn bản gốc có đóng dấu đỏ.",
    en: "> **[DISCLAIMER]** This document was generated by AI for educational and reference purposes. The content is based on the original Vietnamese legal text. For legal purposes, please refer to the official signed Vietnamese version.",
    ja: "> **[DISCLAIMER]** 本文書はAIにより生成されたものであり、学習および参照を目的としています。内容はベトナム語の公式法的文書に基づいています。法的効力については、署名・捺印された公式のベトナム語原文を優先してください。"
};

function processFile(filePath) {
    const filename = path.basename(filePath);
    let prefix = null;
    for (const key in batchDocs) {
        if (filename.startsWith(key)) {
            prefix = key;
            break;
        }
    }
    if (!prefix) return;

    const meta = batchDocs[prefix];
    const lang = filename.endsWith('_en.md') ? 'en' : filename.endsWith('_ja.md') ? 'ja' : 'vi';
    const isTranscription = (lang === 'vi');

    let content = fs.readFileSync(filePath, 'utf-8');
    const today = new Date().toISOString().split('T')[0];

    // 1. Construct YAML
    const yaml = `---
doc_id: "${meta.doc_id}"
title: "${meta.title}"
date: ${meta.date}
department: "${meta.department}"
type: "${meta.type}"
restricted: false
last_updated: ${today}
---`;

    // 2. Remove old YAML and header notes
    content = content.replace(/^---[\s\S]*?---\n*/, '');
    content = content.replace(/<div class="source-note"[\s\S]*?<\/div>\n*/g, '');
    content = content.replace(/^> \*\*\[(?:DISCLAIMER|免責事項|TUYÊN BỐ TỪ CHỐI TRÁCH NHIỆM)\]\*\*.*\n*/gm, '');

    let mainBody = content.trim();

    // 3. Normalization logic
    const lines = mainBody.split('\n');
    let newLines = [];
    let titleSectionDone = false;

    for (let i = 0; i < lines.length; i++) {
        let line = lines[i];
        let cleanLine = line.replace(/^#+ /, '').replace(/\*\*+/g, '').trim();

        // Check for Chapter/Article markers
        const isChapter = /^(Chương|Chapter|第[0-9一二三四五六七八九十百]+章)/i.test(cleanLine);
        const isArticle = /^(Điều|Article|第[0-9一二三四五六七八九十百]+条)/i.test(cleanLine);

        if (isChapter || isArticle) {
            titleSectionDone = true;
            if (isTranscription) {
                // VI: Chapter -> #, Article -> ##
                line = (isChapter ? '# ' : '## ') + cleanLine;
            } else {
                // EN/JA: Chapter -> #, Article -> ## (avoid later bad_h3_article cleanup)
                line = (isChapter ? '# ' : '## ') + cleanLine;
            }
        } else if (!titleSectionDone && i < 40) {
            // Centering titles (before first Chapter/Article)
            const isHeaderMarker = line.startsWith('#');
            if (cleanLine.length > 0 && !line.startsWith('<p align="center">') && !line.startsWith('---') && !line.startsWith('***')) {
                if (isHeaderMarker || (line.startsWith('**') && line.endsWith('**')) || cleanLine.toUpperCase() === cleanLine) {
                    line = `<p align="center"><strong>${cleanLine}</strong></p>`;
                }
            }
        }

        // List indentation
        if (/^[ \t]+(\d+\.\s+)/.test(line)) {
            line = line.replace(/^[ \t]+(\d+\.\s+)/, '$1');
        }
        if (/^[ \t]{0,1}-\s+(.*)/.test(line)) {
            line = line.replace(/^[ \t]{0,1}-\s+(.*)/, '  - $1');
        }

        newLines.push(line);
    }

    mainBody = newLines.join('\n');

    // Separator spacing & cleanup
    mainBody = mainBody.replace(/([^\n])\n\*\*\*\n([^\n])/g, '$1\n\n***\n\n$2');
    mainBody = mainBody.replace(/<p align="center"><strong><p align="center"><strong>(.*)<\/strong><\/p><\/strong><\/p>/g, '<p align="center"><strong>$1</strong></p>');

    // Final cleanup of extra newlines
    mainBody = mainBody.replace(/\n{3,}/g, '\n\n');

    const finalContent = `${yaml}\n\n${disclaimers[lang]}\n\n${mainBody}`;

    fs.writeFileSync(filePath, finalContent, 'utf-8');
    console.log(`[PROCESSED] ${filename} (${lang})`);
}

function main() {
    const files = fs.readdirSync(dataDir);
    for (const docPrefix in batchDocs) {
        const docFiles = files.filter(f => f.startsWith(docPrefix) && f.endsWith('.md'));
        docFiles.forEach(file => {
            processFile(path.join(dataDir, file));
        });
    }
}

main();
