const fs = require('fs');
const path = require('path');

const dataDir = path.resolve(__dirname, '../data');

const batchDocs = {
    '04-2020-TT-BGDDT': {
        doc_id: "04/2020/TT-BGDĐT",
        title: "Quy định về hợp tác, đầu tư của nước ngoài trong lĩnh vực giáo dục",
        date: "2020-03-18",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    '04-2016-TT-BGDDT': {
        doc_id: "04/2016/TT-BGDĐT",
        title: "Ban hành Quy định về tiêu chuẩn đánh giá chất lượng chương trình đào tạo các trình độ của giáo dục đại học",
        date: "2016-03-14",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    '39-2020-TT-BGDDT': {
        doc_id: "39/2020/TT-BGDĐT",
        title: "Ban hành Quy định về tiêu chuẩn đánh giá chất lượng chương trình đào tạo từ xa trình độ đại học",
        date: "2020-10-09",
        department: "Ministry of Education and Training",
        type: "Circular"
    },
    '24-2023-ND-CP': {
        doc_id: "24/2023/NĐ-CP",
        title: "Quy định mức lương cơ sở đối với cán bộ, công chức, viên chức và lực lượng vũ trang",
        date: "2023-05-14",
        department: "Government",
        type: "Decree"
    },
    '78-2022-QD-TTCP': {
        doc_id: "78/2022/QĐ-TTg",
        title: "Phê duyệt Chương trình “Phát triển hệ thống bảo đảm và kiểm định chất lượng giáo dục đối với giáo dục đại học và cao đẳng sư phạm giai đoạn 2022 - 2030”",
        date: "2022-06-28",
        department: "Government",
        type: "Decision"
    }
};

const disclaimers = {
    vi: "> **[DISCLAIMER]** Tài liệu này được tạo bởi AI phục vụ mục đích học tập và tham khảo. Nội dung gốc tiếng Việt được trích xuất từ văn bản chính thức. Mọi thông tin có tính pháp lý phải được đối chiếu với văn bản gốc có đóng dấu đỏ.",
    en: "> **[DISCLAIMER]** This document was generated by AI for educational and reference purposes. The content is based on the original Vietnamese legal text. For legal purposes, please refer to the official signed Vietnamese version.",
    ja: "> **[DISCLAIMER]** 本文書はAIにより生成されたものであり、学習および参照を目的としています。内容はベトナム語の公式法的文書に基づいています。法的効力については、署名・捺印された公式のベトナム語原文を優先してください。"
};

function processFile(filePath) {
    const filename = path.basename(filePath);
    let prefix = null;
    for (const key in batchDocs) {
        if (filename.startsWith(key)) {
            prefix = key;
            break;
        }
    }
    if (!prefix) return;

    const meta = batchDocs[prefix];
    const lang = filename.endsWith('_en.md') ? 'en' : filename.endsWith('_ja.md') ? 'ja' : 'vi';
    const isTranscription = (lang === 'vi');

    let content = fs.readFileSync(filePath, 'utf-8');
    // 1. Construct YAML
    const yaml = `---
doc_id: "${meta.doc_id}"
title: "${meta.title}"
date: ${meta.date}
department: "${meta.department}"
type: "${meta.type}"
restricted: false
---`;

    // 2. Remove old YAML, header notes, and specific junk
    content = content.replace(/^---[\s\S]*?---\n*/, '');
    content = content.replace(/<div class="source-note"[\s\S]*?<\/div>\n*/g, '');
    content = content.replace(/<div class="doc-note"[\s\S]*?<\/div>\n*/g, '');
    content = content.replace(/^> \*\*\[(?:DISCLAIMER|免責事項|TUYÊN BỐ TỪ CHỐI TRÁCH NHIỆM)\]\*\*.*\n*/gm, '');

    let mainBody = content.trim();

    // 3. Normalization logic
    const lines = mainBody.split('\n');
    let newLines = [];
    let titleSectionDone = false;

    for (let i = 0; i < lines.length; i++) {
        let line = lines[i];

        // Normalize existing HTML headers
        line = line.replace(/<h[1-6] align="center">(.*?)<\/h[1-6]>/g, '<p align="center"><strong>$1</strong></p>');

        let cleanLine = line.replace(/^#+ /, '').replace(/\*\*+/g, '').replace(/<[^>]*>/g, '').trim();

        // Check for Chapter/Article markers
        const isChapter = /^(Chương|Chapter|第[0-9一二三四五六七八九十百]+章)/i.test(cleanLine);
        const isArticle = /^(Điều|Article|第[0-9一二三四五六七八九十百]+条)/i.test(cleanLine);

        if (isChapter || isArticle) {
            titleSectionDone = true;
            if (isTranscription) {
                // VI: Chapter -> #, Article -> ##
                line = (isChapter ? '# ' : '## ') + cleanLine;
            } else {
                // EN/JA: Chapter -> #, Article -> ## (avoid later bad_h3_article cleanup)
                line = (isChapter ? '# ' : '## ') + cleanLine;
            }
        } else if (!titleSectionDone && i < 60) {
            // Centering titles (before first Chapter/Article)
            const isHeaderMarker = line.startsWith('#');
            const isPAlignCenter = line.startsWith('<p align="center">');

            if (cleanLine.length > 0 && !isPAlignCenter && !line.startsWith('---') && !line.startsWith('***') && !line.startsWith('|')) {
                if (isHeaderMarker || (line.startsWith('**') && line.endsWith('**')) || cleanLine.toUpperCase() === cleanLine || (i < 10 && cleanLine.length < 100)) {
                    line = `<p align="center"><strong>${cleanLine}</strong></p>`;
                }
            }
        }

        // List indentation
        if (/^[ \t]+(\d+\.\s+)/.test(line)) {
            line = line.replace(/^[ \t]+(\d+\.\s+)/, '$1');
        }
        if (/^[ \t]{0,1}-\s+(.*)/.test(line)) {
            line = line.replace(/^[ \t]{0,1}-\s+(.*)/, '  - $1');
        }

        newLines.push(line);
    }

    mainBody = newLines.join('\n');

    // Separator spacing & cleanup
    mainBody = mainBody.replace(/([^\n])\n\*\*\*\n([^\n])/g, '$1\n\n***\n\n$2');
    mainBody = mainBody.replace(/<p align="center"><strong><p align="center"><strong>(.*)<\/strong><\/p><\/strong><\/p>/g, '<p align="center"><strong>$1</strong></p>');

    // Clean up weird terminology fragments if any (specific fix for 04-2016-TT-BGDDT)
    mainBody = mainBody.replace(/4\. Education Testing and 2\. Quality Assurance/g, 'Quality Assurance and Accreditation');

    // Final cleanup of extra newlines
    mainBody = mainBody.replace(/\n{3,}/g, '\n\n');

    const finalContent = `${yaml}\n\n${disclaimers[lang]}\n\n${mainBody}`;

    fs.writeFileSync(filePath, finalContent, 'utf-8');
    console.log(`[PROCESSED] ${filename} (${lang})`);
}

function main() {
    const files = fs.readdirSync(dataDir);
    for (const docPrefix in batchDocs) {
        const docFiles = files.filter(f => f.startsWith(docPrefix) && f.endsWith('.md'));
        docFiles.forEach(file => {
            processFile(path.join(dataDir, file));
        });
    }
}

main();
